/* Objetos simbólicos que viajan entre escenas y notas del presentador.
   keys: [idEscena, beat, {x, y (centro en px del escenario 1920×1080), s escala, r grados, o opacidad}] */
window.DECK_OBJECTS = {
  orbe: { src: 'assets/orbe.webp', w: 260, glow: true, keys: [
    ['portada', 2, { x: 1737, y: 60, s: .35, o: 0 }],
    ['deseo', 0, { x: 1370, y: 560, s: 1 }],
    ['deseo', 2, { x: 1370, y: 560, s: .62, o: .45 }],
    ['eden', 0, { x: 1370, y: 560, s: .4, o: 0 }],
    ['receta', 0, { x: 1520, y: 405, s: .8 }],
    ['receta', 2, { x: 1520, y: 405, s: .5, o: 0 }],
    ['entrego', 0, { x: 410, y: 720, s: .62 }],
    ['getsemani', 0, { x: 410, y: 720, s: .4, o: 0 }],
  ] },
  llave: { src: 'assets/llave.webp', w: 240, glow: true, keys: [
    ['deseo', 1, { x: 1370, y: -120, r: -70, s: .6, o: 0 }],
    ['deseo', 2, { x: 1370, y: 560, r: -20, s: 1.05 }],
    ['eden', 0, { x: 1370, y: 560, s: .6, o: 0 }],
    ['lecturas', 1, { x: 300, y: 1000, r: -40, s: .4, o: 0 }],
    ['lecturas', 2, { x: 455, y: 925, r: -15, s: .55 }],
    ['idioma', 0, { x: 300, y: 290, r: -15, s: .55 }],
    ['receta', 0, { x: 400, y: 405, r: -25, s: .78 }],
    ['receta', 2, { x: 400, y: 405, s: .5, o: 0 }],
    ['entrego', 0, { x: 410, y: 470, r: -20, s: .7 }],
    ['entrego', 1, { x: 1500, y: 470, r: 0, s: .72 }],
    ['getsemani', 0, { x: 1500, y: 470, s: .4, o: 0 }],
  ] },
  serpiente: { src: 'assets/serpiente.webp', w: 230, keys: [
    ['reves', 3, { x: 960, y: 330, s: .5, r: -90, o: 0 }],
    ['lecturas', 0, { x: 960, y: 320, s: 1, r: 0 }],
    ['idioma', 0, { x: 960, y: 320, s: .6, r: 90, o: 0 }],
  ] },
  caliz: { src: 'assets/caliz.webp', w: 380, glow: true, keys: [
    ['getsemani', 3, { x: 1226, y: 200, s: .2, o: 0 }],
    ['caliz', 0, { x: 960, y: 540, s: 1 }],
    ['caliz', 4, { x: 960, y: 560, s: .85 }],
    ['jardines', 0, { x: 960, y: 560, s: .5, o: 0 }],
    ['canto', 2, { x: 560, y: 470, s: .4, o: 0 }],
    ['caliz2', 0, { x: 560, y: 470, s: .75 }],
    ['pregunta', 0, { x: 560, y: 470, s: .5, o: 0 }],
  ] },
  vela: { src: 'assets/vela.webp', w: 300, glow: true, keys: [
    ['teresita', 3, { x: 960, y: 1120, s: .3, o: 0 }],
    ['noche', 0, { x: 960, y: 985, s: .32 }],
    ['canto', 0, { x: 400, y: 540, s: 1.25 }],
    ['caliz2', 0, { x: 1360, y: 470, s: .85 }],
    ['pregunta', 0, { x: 1360, y: 470, s: .5, o: 0 }],
  ] },
};

window.DECK_NOTES = {
  portada: '<p>Hay algo profundamente humano en querer saber que todo va a salir bien. A veces llamo confianza a un intento más sofisticado de controlar mi vida.</p><p>Recorreremos dos jardines y la historia de una joven que perdió hasta el consuelo de su fe. Dejar respirar la imagen.</p>',
  deseo: '<p>La promesa seduce porque toca deseos legítimos: salud, amor, seguridad, sentido. No caricaturizar a quien busca respuestas.</p><p>Espacio opcional para el testimonio personal de Rogelio (en primera persona, breve y real).</p>',
  eden: '<p>Gn 3,1–6: la serpiente no ofrece destrucción; pone en duda la palabra y las intenciones de Dios. La frase grande es paráfrasis de la insinuación, no cita bíblica.</p><p>El árbol parece deseable para lograr inteligencia.</p>',
  grieta: '<p>Catecismo 397–398: el quiebre es una pérdida de confianza. El deseo de sabiduría no es malo; la ruptura es buscar la plenitud sin Dios, antes que Dios y no según Dios.</p><p>Idea a fijar: el fruto viene después; la sospecha llegó primero.</p>',
  reves: '<p>Algunos relatos antiguos releen el jardín: en <em>La hipóstasis de los arcontes</em> la serpiente es instructora. Ireneo (Contra las herejías I,30) describe doctrinas parecidas, pero escribe como adversario.</p><p>No todo gnosticismo contó el jardín igual.</p>',
  lecturas: '<p>La diferencia es más profunda que una opinión sobre un animal: se conserva la escena, cambia quién parece digno de confianza.</p><p>Pregunta que sigue viva: ¿recibo mi vida de Dios o descubro una clave que Él no me dio?</p>',
  idioma: '<p>No hay una línea recta del manuscrito antiguo a la app moderna; sí una familia de motivos. El documento vaticano de 2003 describe raíces esotéricas y gnósticas de la Nueva Era y la Sociedad Teosófica (Blavatsky y Olcott, Nueva York, 1875).</p><p>Escuchar qué promete cada propuesta, no sólo sus palabras.</p>',
  receta: '<p>No describe toda meditación ni toda búsqueda de bienestar. Hablo de propuestas que atribuyen al estado interior la capacidad de atraer o producir acontecimientos externos.</p><p>¿Escucho a Alguien o aplico una técnica?</p>',
  secret: '<p>La página oficial de <em>The Secret</em> sostiene que los pensamientos atraen objetos, personas y experiencias: no sólo que pensar distinto cambia decisiones.</p><p>Por qué atrae a quien teme por dinero o salud; y la presión posible de vigilar cada temor. Consecuencia posible, no atribuible a todos los lectores.</p>',
  tres: '<p>La editorial de <em>Deja de ser tú</em> lo presenta con lenguaje de física cuántica y neurociencia: propuesta editorial, no demostración. Conny Méndez, <em>Metafísica 4 en 1</em>: leyes mentales y vocabulario religioso.</p><p>No son idénticos. Pregunta común: ¿qué espero que produzca mi práctica interior?</p>',
  suelta: '<p>Dispenza (The Balance Between Intention and Surrender): intención clara, emoción elevada y luego entregar el «cómo». Habla de confiar y no forzar los medios. Por eso «ellos controlan, nosotros soltamos» sería mala comparación.</p><p>¿Cuando suelto el método entrego también el desenlace? La pintura es interpretación visual, no ilustración literal de Dispenza.</p>',
  entrego: '<p>Puedo dejar los detalles y seguir convencido de que mi vida espiritual debe producir un resultado específico. Examinarlo en nosotros, aunque nunca hayamos leído <em>The Secret</em>.</p><p>La oración cristiana también puede volverse trato. Llevemos esta pregunta al segundo jardín.</p>',
  getsemani: '<p>Mc 14,32–42: Jesús no es imperturbable. Pide compañía, siente espanto y angustia, ruega que pase la hora. Sus amigos no logran velar.</p><p>La confianza empieza dentro del miedo.</p>',
  caliz: '<p>Jesús no niega su deseo: pide que se aparte el cáliz. La frase decisiva no borra el deseo; lo entrega. Luego se levanta y camina hacia lo que llega.</p><p>Benedicto XVI (1 feb 2012): Adán y Eva buscaron la libertad en el «no»; Jesús reconduce la voluntad humana al «sí».</p>',
  jardines: '<p>En un jardín la abundancia no impide sospechar de Dios; en el otro la angustia no impide entregarse a Él.</p><p>Mi estado emocional no es la medida completa de mi relación con Dios.</p>',
  teresita: '<p>Teresita entró muy joven al Carmelo. En la noche del Jueves al Viernes Santo de 1896 apareció sangre, signo de la enfermedad que terminaría con su vida. Al principio imaginó con alegría el encuentro con Jesús.</p><p>Después comenzó una gran prueba de la fe (archivos del Carmelo de Lisieux).</p>',
  noche: '<p>La idea de la muerte empezó a encontrarse con oscuridad interior y la tentación de que no hubiera nada. No decidió abandonar la fe: describió un combate.</p><p><em>C’est la confiance</em> 25 la llama «prueba contra la fe». No reducirlo a un día sin emoción agradable.</p>',
  canto: '<p>Manuscrito C: canta sobre la alegría del cielo sin sentirla; canta lo que quiere creer (traducción citada en <em>C’est la confiance</em> 42).</p><p>Su fe no es técnica para recuperar el consuelo: permanece en una ausencia que no controla.</p>',
  caliz2: '<p>Carta del 17 de septiembre de 1896 a su hermana María: sus grandes deseos no son el fundamento de su confianza; recuerda a Jesús pidiendo que se aparte el cáliz. La conexión con Getsemaní en su propia voz.</p><p>No obtiene salud como premio por sentir correctamente.</p>',
  pregunta: '<p>¿Hay algo que le pido a Dios y, en el fondo, considero que no debería negarme? ¿Cuando digo «hágase tu voluntad», confío en su bondad o supongo que esa frase me conseguirá lo que quiero?</p><p>Silencio. Escuchar sin convertirlo en examen sobre prácticas ajenas.</p>',
  cierre: '<p>Confiar no es aprender la fórmula que garantiza un desenlace: es pedir con sinceridad, actuar con responsabilidad y seguir viviendo como hijo. Edén: sospecha. Getsemaní: entrega en la angustia. Teresita: fidelidad en la oscuridad.</p><p>Oración final si encaja con el grupo.</p>',
};
