window.CORAZON_REMASTER = [
  {chapter:'Del ocultismo a Cristo',title:'CORAZÓN <em>INQUIETO</em>',subtitle:'Del ocultismo a Cristo',style:'hero',notes:'Presentar la historia como una búsqueda real. La pregunta final será dónde busca descanso el corazón.'},
  {chapter:'Antes',title:'ANTES',style:'hero',notes:'Mostrar al Pepe de antes. Los detalles personales se cuentan desde el guion privado.'},
  {chapter:'El comienzo',title:'ALEMANIA',subtitle:'Una búsqueda lejos de casa.',notes:'Situar el comienzo de esta etapa en Alemania.'},
  {chapter:'La falsa luz',title:'EL DESPERTAR <em>DEL ORGULLO</em>',quote:'«Yo creí que había despertado».',style:'small-title',notes:'La trampa fue creer que conocer algo oculto me colocaba por encima de los demás.'},
  {chapter:'Génesis 3,5',title:'LA PRIMERA <em>TENTACIÓN</em>',quote:'«Seréis como dioses».',attribution:'Génesis 3,5',notes:'Leer el contexto de Génesis 3. La promesa se apoya en la desconfianza hacia Dios.'},
  {chapter:'Un eco a través del tiempo',title:'LA MISMA <em>MENTIRA</em>',subtitle:'Cambian las formas. Persiste la promesa de ser dueño de la verdad.',lineage:['Edén','Lecturas gnósticas','Hermetismo','Nueva Era'],style:'small-title',notes:'Presentar estas etapas como ecos y apropiaciones, no como una genealogía lineal demostrada.'},
  {chapter:'Seis años',title:'EL LABERINTO',subtitle:'Seis años buscando en la oscuridad.',notes:'Dejar que la imagen cargue la sensación de avance aparente y desorientación real.'},
  {chapter:'Una puerta más',title:'EL <em>KYBALION</em>',subtitle:'La promesa de comprender las leyes ocultas del universo.',notes:'El Kybalion es una obra del siglo XX atribuida a los Tres Iniciados.'},
  {chapter:'El Kybalion',title:'SIETE <em>PRINCIPIOS</em>',list:['Mentalismo','Correspondencia','Vibración','Polaridad','Ritmo','Causa y efecto','Género'],style:'small-title',notes:'Nombrar los siete principios atribuidos por el libro, sin presentarlos como leyes científicas.'},
  {chapter:'1905–1972',title:'NEVILLE <em>GODDARD</em>',subtitle:'El falso profeta.',notes:'Explicar su influencia en la espiritualidad de manifestación. “Falso profeta” es un juicio teológico del testimonio, no un dato biográfico.'},
  {chapter:'La interpretación cambia',title:'CÓMO TORCIÓ <em>EL EVANGELIO</em>',subtitle:'La Escritura dejó de hablarme de Cristo y empezó a hablarme de mi poder.',style:'small-title',notes:'Contrastar el sentido cristiano con una lectura que convierte los personajes bíblicos en estados de conciencia.'},
  {chapter:'La búsqueda se estrecha',title:'LOS CÍRCULOS <em>OSCUROS</em>',notes:'Contar la experiencia sin sugerir que cada práctica o persona mencionada comparte el mismo origen o efecto.'},
  {chapter:'Discernimiento',title:'EL CATÁLOGO <em>DEL ENGAÑO</em>',subtitle:'No toda promesa de poder espiritual conduce a la verdad.',list:['Adivinación','Manifestación','Energías','Rituales','Entidades','Esoterismo'],style:'small-title small-copy',notes:'Discernir prácticas concretas sin acusar indiscriminadamente a toda terapia, meditación o filosofía.'},
  {chapter:'Una presencia fiel',title:'LA PACIENCIA <em>DE UN AMIGO</em>',subtitle:'Alguien permaneció cerca cuando yo no podía salir solo.',notes:'Contar la amistad real detrás de esta lámina.'},
  {chapter:'El quiebre',title:'EL FONDO <em>DEL POZO</em>',notes:'Pausa. Permitir que el peso de este momento se sienta.'},
  {chapter:'Eclesiastés 1,2',title:'ECLESIASTÉS',quote:'«Vanidad de vanidades, todo es vanidad».',attribution:'Eclesiastés 1,2',notes:'La frase dio nombre al vacío; no fue una solución instantánea.'},
  {chapter:'Confesiones I,1',title:'UN CORAZÓN <em>INQUIETO</em>',quote:'«Nos hiciste, Señor, para ti, y nuestro corazón está inquieto hasta que descanse en ti».',attribution:'San Agustín · Confesiones I,1',style:'small-title quote-heavy',notes:'Leer la frase de san Agustín. Es el eje del testimonio.'},
  {chapter:'San Agustín',title:'EL ECO A TRAVÉS <em>DEL TIEMPO</em>',subtitle:'Otro hombre también buscó descanso donde no podía encontrarlo.',style:'small-title',notes:'Usar a Agustín como espejo espiritual sin equiparar biografías distintas.'},
  {chapter:'Lucas 15,11–32',title:'EL HIJO <em>PRÓDIGO</em>',quote:'«Yo era ese hijo».',notes:'Contar el regreso desde la perspectiva del hijo; el centro de la parábola es la misericordia del padre.'},
  {chapter:'La raíz',title:'SOBERBIA',subtitle:'La ilusión de bastarme a mí mismo.',lineage:['«No serviré»','«Seréis como dioses»','«Yo desperté»','¿Y tú?'],style:'small-title',notes:'“Non serviam” no es una cita literal de Lucifer en la Biblia.'},
  {chapter:'Dos caminos',title:'EL <em>CONTRASTE</em>',subtitle:'Controlarlo todo o dejarme encontrar.',notes:'Contrastar la búsqueda de poder con la libertad de ser amado.'},
  {chapter:'Una vida nueva',title:'LA <em>TRANSFORMACIÓN</em>',notes:'Nombrar los cambios reales que Rogelio quiera hacer públicos; no prometer una vida sin lucha.'},
  {chapter:'La lucha continúa',title:'LA GUERRA <em>ESPIRITUAL</em>',subtitle:'No todo terminó en el momento de volver.',notes:'Presentar la vida espiritual como perseverancia.'},
  {chapter:'San Miguel Arcángel',title:'¿QUIÉN COMO <em>DIOS?</em>',style:'hero',notes:'Pausa visual con san Miguel frente al dragón. La frase tradicional explica su nombre.'},
  {chapter:'El centro',title:'LA PRESENCIA <em>REAL</em>',notes:'Hablar del encuentro con Cristo en la Eucaristía desde la fe católica del testimonio.'},
  {chapter:'La victoria de Cristo',title:'ÉL <em>VENCIÓ</em>',style:'hero',notes:'El centro de la esperanza no es mi fuerza ni mis técnicas: es Cristo.'},
  {chapter:'Una libertad recibida',title:'LA VICTORIA <em>SOBRE EL MAL</em>',notes:'No usar la victoria como triunfalismo. La libertad se recibe y se cuida.'},
  {chapter:'Después',title:'DESPUÉS',style:'hero',notes:'Mostrar a Pepe después. No implica perfección; sí una dirección distinta.'},
  {chapter:'Descanso',title:'MI CORAZÓN YA <em>NO ESTÁ INQUIETO</em>',quote:'«Nuestro corazón está inquieto hasta que descanse en ti».',attribution:'San Agustín · Confesiones I,1',style:'small-title quote-heavy',notes:'Cerrar el arco de “Antes” y “Después” con la frase de Agustín.'},
  {chapter:'Una pregunta para todos',title:'¿DÓNDE ESTÁ BUSCANDO <em>TU CORAZÓN?</em>',style:'small-title',notes:'Dejar la pregunta abierta para que la conversación surja naturalmente.'}
];
